In [3]:
import torch
print(torch.__version__)


2.12.0+cu130


Introduction to tensors


In [4]:
#scalar
sca=torch.tensor(7)
sca

tensor(7)

In [5]:
vector1=torch.tensor([7,8])
vector1

tensor([7, 8])

In [6]:
vector1.ndim

1

In [7]:
#Checking the dimensions of the tensor
sca.ndim


0

In [8]:
#Converting the scalar to normal python int
sca.item()

7

In [9]:
#Creating an vector 

vector=torch.tensor([7,8,9])
vector

tensor([7, 8, 9])

In [10]:
#Let's check the dimension of the vector

vector.ndim

1

In [11]:
vector.shape

torch.Size([3])

In [12]:
#Creating an MATRIX
MATRIX=torch.tensor([[7,5]])
MATRIX

tensor([[7, 5]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0][0]

tensor(7)

In [15]:
#Let's create an TENSOR
TENSOR=torch.tensor([[[0,3,1,4],
                    [9,10,6,1],
                    [7,60,9,3],]])
TENSOR

tensor([[[ 0,  3,  1,  4],
         [ 9, 10,  6,  1],
         [ 7, 60,  9,  3]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR[0][1][2]

tensor(6)

In [18]:
TENSOR.shape

torch.Size([1, 3, 4])

In [19]:
TENSOR.item

<function Tensor.item>

#Creating a random tensor

In [20]:
rn=torch.rand(4,3)
rn

tensor([[0.0125, 0.5672, 0.2152],
        [0.4326, 0.6734, 0.3019],
        [0.7381, 0.9285, 0.3527],
        [0.3208, 0.2746, 0.2395]])

In [21]:
#Creating the tensor with the image

image_random_tensor=torch.rand(3,255,255)

image_random_tensor.shape, image_random_tensor.ndim


(torch.Size([3, 255, 255]), 3)

Zeros and one

In [22]:
#Creating the tensor of all zeroes
zero= torch.zeros(size=(4,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zero*rn

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
#Creating the tensor of one

one=torch.ones(size=(4,3))
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
one.dtype

torch.float32

Creating a range of tensor and tensor-like

In [26]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
one_to_ten=torch.arange(start=1,end=51,step=10)
one_to_ten

tensor([ 1, 11, 21, 31, 41])

In [28]:
ten_zero=torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

PyTorch Datatype


In [29]:
float_32=torch.tensor([3.0,6.0,9.0],
                      dtype=None,
                      device=None,
                      requires_grad=False)
float_32

tensor([3., 6., 9.])

In [30]:
float_32.dtype

torch.float32

In [31]:
float_16=float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16 * float_32

tensor([ 9., 36., 81.])

Find out details about some tensor

In [33]:
#Create a tensor

some_tensor=torch.rand(4,5).type(torch.float16)
some_tensor

tensor([[0.6860, 0.3884, 0.2438, 0.5200, 0.2681],
        [0.0588, 0.9668, 0.2529, 0.8843, 0.8447],
        [0.5767, 0.0519, 0.4365, 0.0130, 0.1669],
        [0.6685, 0.3860, 0.8579, 0.5117, 0.8975]], dtype=torch.float16)

In [34]:
#Find out the details about some tensors

print(some_tensor)
print(f"Data type of the tensor is {some_tensor.dtype}")
print(f"Shape of the tensor {some_tensor.shape}")
print(f"Check the device of the tensor is on {some_tensor.device}")

tensor([[0.6860, 0.3884, 0.2438, 0.5200, 0.2681],
        [0.0588, 0.9668, 0.2529, 0.8843, 0.8447],
        [0.5767, 0.0519, 0.4365, 0.0130, 0.1669],
        [0.6685, 0.3860, 0.8579, 0.5117, 0.8975]], dtype=torch.float16)
Data type of the tensor is torch.float16
Shape of the tensor torch.Size([4, 5])
Check the device of the tensor is on cpu


According to the upper calculation we got that the tensor with the 



In [35]:
#Matrix Multiplication 
tensor1=torch.tensor([[4,3],
                      [2,1],
                      [0,2]])
tensor2=torch.tensor([[3,7],
                      [4,8],
                      [1,2]])
torch.matmul(tensor1.T,tensor2)

tensor([[20, 44],
        [15, 33]])

In [36]:
#Matrix multiplication by hand
tensor=torch.tensor([[45,7],
                     [78,6]])
value=0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor([8109,   85])


In [37]:
#Two main rule of matrix multiplication

mat=torch.tensor([[5,8,7,5,3],
                 [5,8,7,5,3]])
print(mat.shape)
print(mat.ndim)


torch.Size([2, 5])
2


In [41]:
arr=([4,8,9])
print(arr[:5])

[4, 8, 9]


In [48]:
%%time
#Multiplying some matrix

mat_1=torch.tensor([[7,8,9],
                    [8,9,7],
                    [8,1,10]])
mat_2=torch.tensor([[2,0,12],
                    [5,1,11],
                    [100,3,2]])

print(torch.matmul(mat_1,mat_2))
print(mat_1@mat_2)




tensor([[ 954,   35,  190],
        [ 761,   30,  209],
        [1021,   31,  127]])
tensor([[ 954,   35,  190],
        [ 761,   30,  209],
        [1021,   31,  127]])
CPU times: total: 0 ns
Wall time: 999 μs


In [70]:
#Finding min,max,mean,sum etc

tensor1=torch.tensor([[7,8,9],
                    [8,19,7],
                    [8,1,10]])
rang=torch.arange(10,100,10)
print(torch.min(rang))
print(torch.max(tensor1))
print(torch.mean(rang.type(torch.float64)))
print(torch.sum(tensor1))
print(torch.argmin(rang))

tensor(10)
tensor(19)
tensor(50., dtype=torch.float64)
tensor(77)
tensor(0)


In [ ]:
#Reshape,squeeze,unsqueeze

reshape=rang.reshape(9)
squeeze=tensor1.squeeze()
print(squeeze.shape)

print(reshape.shape,reshape)

torch.Size([3, 3])
torch.Size([9]) tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
